services:
  web:
    env_file:
      - ./.env
    container_name: budget-app-web
    build: .
    image: budget-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}


  db:
    image: postgres
    container_name: budget-app-db
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
