name: Build and Deploy

on:
  push:
    branches:
      - main
      - release

jobs:
  pr-checks:
    name: PR Checks
    uses: ./.github/workflows/PR-checks.yml

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [pr-checks]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: /src
          push: false
          tags: ${{ vars.ECR_REPO }}/budget-app:$GITHUB_SHA

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          image-ref: ${{ vars.ECR_REPO }}/budget-app:$GITHUB_SHA
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"



