name: Build and Deploy

on:
  push:
    branches:
      - main
      - release

permissions:
  id-token: write
  contents: read 

jobs:
  pr-checks:
    name: PR Checks
    uses: ./.github/workflows/PR-checks.yml
    secrets: inherit

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [pr-checks]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Determine TF workspace
        run: |
          if [[ $GITHUB_REF == 'refs/heads/release' ]]; then
            echo "release" > .workspace
          else
            echo "staging" > .workspace
          fi

      - name: Read TF workspace value
        id: determine_workspace
        uses: guibranco/github-file-reader-action-v2@latest
        with:
          path: ".workspace"

      - name: Check for TF setup change
        uses: dorny/paths-filter@v3
        id: setup_changed
        with:
          filters: |
            setup:
              - 'terraform/setup/**'

      - name: Terraform apply setup
        if: steps.setup_changed.outputs.setup == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_WS: "${{ steps.determine_workspace.outputs.contents }}"
        working-directory: "terraform"
        run: |
          TF_CMD="docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=setup/"
          $TF_CMD init
          $TF_CMD workspace select -or-create $TF_WS
          $TF_CMD apply -auto-approve

      - name: Log in to AWS
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ vars.ECR_REPO }}:${{ GITHUB.SHA }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          image-ref: ${{ vars.ECR_REPO }}:${{ GITHUB.SHA }}
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Push the image to ECR
        run: docker push ${{ vars.ECR_REPO }}:${{ GITHUB.SHA }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Determine TF workspace
        run: |
          if [[ $GITHUB_REF == 'refs/heads/release' ]]; then
            echo "release" > .workspace
          else
            echo "staging" > .workspace
          fi

      - name: Read TF workspace value
        id: determine_workspace
        uses: guibranco/github-file-reader-action-v2@latest
        with:
          path: ".workspace"

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          TF_VAR_ecr_app_image: "${{ vars.ECR_REPO }}:${{ GITHUB.SHA }}"
          TF_WS: "${{ steps.determine_workspace.outputs.contents }}"
        working-directory: "terraform"
        run: |
          TF_CMD="docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=deploy/"
          $TF_CMD init
          $TF_CMD workspace select -or-create $TF_WS
          $TF_CMD apply -auto-approve
