name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment for which to destroy the resources.
        options:
          - staging
          - release

jobs:
  destroy:
    name: Destroy resources in AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Terraform destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        run: |
          export TF_WORKSPACE=${{  github.event.inputs.environment }}
          cd terraform/
          docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=deploy/ init
          docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=deploy/ destroy -auto-approve
