name: Setup Environment

on:
  push:
    branches:
      - main
      - release
    paths:
      - terraform/setup/**

permissions:
  id-token: write
  contents: read

jobs:
  tests-and-checks:
    name: Tests and Checks
    uses: ./.github/workflows/tests-and-checks.yml

  login:
    name: Log in to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Set vars
        run: |
          if [[ $GITHUB_REF == 'refs/head/release' ]]; then
            echo "release" > .workspace
          else
            echo "config" > .workspace
          fi

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          workspace=$(cat .workspace)
          cd terraform/
          docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=setup/ init
          docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=setup/ workspace select -or-create $workspace
          docker compose -f docker-compose-terraform-setup.yml run --rm terraform -chdir=setup/ plan





