name: Syntax check and unit tests on push

on:
  push:
   branches:
    - '**' 

jobs:
  editorconfig:
    name: EditorConfig checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run EditorConfig Checker 
        run: editorconfig-checker

  markdownlintcli:
    name: Markdownlint CLI
    runs-on: ubuntu-latest
    steps:
      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli
      
      - name: Run Markdownlint  
        run: markdownlint **/*.md

  python-black:
    name: Run Python Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: datadog/action-py-black-formatter@v2.5
        id: action_black
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1.19.0
        with:
          tool_name: blackfmt 

 # python-pylint:
    #name: Run Pylint Github Action
    #runs-on: ubuntu-latest
    #continue-on-error: true
    #steps:
      #- name: Checkout repo
        #uses: actions/checkout@v4

      #- name: Install dependencies
        #uses: BSFishy/pip-action@v1
        #with:
          #requirements: src/requirements.txt

      #- name: Run Pylint GitHub Action
        #uses: ReasonSoftware/action-pylint@v2.0.4
        #with:
          #filepaths: "src/*.py"
          #options: "-d C0114,C0115,C0116" 

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: src
          plugins: flake8-spellcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unittest:
    name: Run Python unit tests
    runs-on: ubuntu-latest
    needs: [editorconfig,markdownlintcli, python-black, python-lint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Run tests
        uses: BSFishy/pip-action@v1
        with:
          requirements: src/requirements.txt
