name: Syntax check and unit tests on push

on:
  push:
   branches:
    - '**' 

jobs:
  editorconfig:
    name: EditorConfig checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run EditorConfig Checker 
        run: editorconfig-checker

  markdownlintcli:
    name: Markdownlint CLI
    runs-on: ubuntu-latest
    steps:
      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli
      
      - name: Run Markdownlint  
        run: markdownlint **/*.md

  python-black:
    name: Run Python Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Python Black Check
        uses: rodrigogiraoserrao/python-black-check@v3.0
        with:
          line-length: '81'

  python-pylint:
    name: Run Pylint Github Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Pylint GitHub Action
        uses: ReasonSoftware/action-pylint@v2.0.4
        with:
          requirements_file: requirements.txt
          filepaths: "app/*.py"
          options: "-d C0114,C0115,C0116"

  unittest:
    name: Run Python unit tests
    runs-on: ubuntu-latest
    needs: [editorconfig,markdownlintcli, python-black, python-pylint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r /src/requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s src -p "*.py"


